### ISSUE TITLE
Writing CMakeLists.txt with main.cpp

### ISSUE THREAD

**Issue by ghost** [avast-tl/yaracpp#10]
Hello, I wanted to build the static library including the driver program, main.cpp (the example usage program). 
For that I added the following lines to CMakeList.txt inside the yaracpp folder (before the add_subdirectory() commands) : 

add_executable(main main.cpp)

set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -Iinclude -Ibuild/deps/yara/src/yara/libyara/include -Lbuild/src -Lbuild/deps/yara/src/yara/libyara/.libs/ main.cpp ")

target_link_libraries(main yaracpp yara pthread)

But, when I ran the build commands I got the following errors in cmake build command (at the bottom):

cmake --build . -- -j $NPROC
Scanning dependencies of target yara
[  6%] Creating directories for 'yara'
[ 12%] Performing download step (download, verify and extract) for 'yara'
-- Downloading...
   dst='/home/mevasu/yaracpp/build/deps/yara/src/yara.zip'
   timeout='none'
-- Using src='https://github.com/avast/yara/archive/e3ae3848d66cdb551e149f1a87a45bcc87578f9c.zip'
-- verifying file...
       file='/home/mevasu/yaracpp/build/deps/yara/src/yara.zip'
-- Downloading... done
-- extracting...
     src='/home/mevasu/yaracpp/build/deps/yara/src/yara.zip'
     dst='/home/mevasu/yaracpp/build/deps/yara/src/yara'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 25%] No update step for 'yara'
[ 25%] No patch step for 'yara'
[ 31%] No configure step for 'yara'
[ 37%] Performing configure-linux step for 'yara'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:20: installing 'build-aux/ar-lib'
configure.ac:20: installing 'build-aux/compile'
configure.ac:28: installing 'build-aux/config.guess'
configure.ac:28: installing 'build-aux/config.sub'
configure.ac:8: installing 'build-aux/install-sh'
configure.ac:8: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
configure.ac: installing 'build-aux/ylwrap'
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... /usr/bin/cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/cc accepts -g... yes
checking for /usr/bin/cc option to accept ISO C89... none needed
checking whether /usr/bin/cc understands -c and -o together... yes
checking dependency style of /usr/bin/cc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for gcc... (cached) /usr/bin/cc
checking whether we are using the GNU C compiler... (cached) yes
checking whether /usr/bin/cc accepts -g... (cached) yes
checking for /usr/bin/cc option to accept ISO C89... (cached) none needed
checking whether /usr/bin/cc understands -c and -o together... (cached) yes
checking dependency style of /usr/bin/cc... (cached) gcc3
checking for flex... no
checking for lex... no
checking for bison... no
checking for byacc... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by /usr/bin/cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from /usr/bin/cc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... /usr/bin/cc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /usr/bin/cc supports -fno-rtti -fno-exceptions... no
checking for /usr/bin/cc option to produce PIC... -fPIC -DPIC
checking if /usr/bin/cc PIC flag -fPIC -DPIC works... yes
checking if /usr/bin/cc static flag -static works... yes
checking if /usr/bin/cc supports -c -o file.o... yes
checking if /usr/bin/cc supports -c -o file.o... (cached) yes
checking whether the /usr/bin/cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking whether byte ordering is bigendian... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking whether to check for GCC pthread/shared inconsistencies... yes
checking whether -pthread is sufficient with -shared... yes
checking for isnan in -lm... yes
checking for log2 in -lm... yes
checking for strlcpy... no
checking for strlcat... no
checking for memmem... yes
checking for timegm... yes
checking for _mkgmtime... no
configure: WARNING:

*****************************************************************
  Could not find OpenSSL library. Some features in "pe" module
  have been disabled. If you want to enable all features please
  install OpenSSL and run this script again.
*****************************************************************

checking for Microsoft Crypto API... checking for wincrypt.h... no
checking for MacOSX Common Crypto API... checking CommonCrypto/CommonCrypto.h usability... no
checking CommonCrypto/CommonCrypto.h presence... no
checking for CommonCrypto/CommonCrypto.h... no
configure: WARNING:

*****************************************************************
  Could not find alternative APIs for hash functions. The "hash"
  module has been disabled.
*****************************************************************
            
checking stdbool.h usability... yes
checking stdbool.h presence... yes
checking for stdbool.h... yes
checking for clock_gettime... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libyara/Makefile
config.status: creating libyara/yara.pc
config.status: executing depfiles commands
config.status: executing libtool commands
[ 43%] Performing build step for 'yara'
Making all in libyara
  CC       grammar.lo
  CC       arena.lo
  CC       ahocorasick.lo
  CC       atoms.lo
  CC       bitmask.lo
  CC       compiler.lo
  CC       endian.lo
  CC       exec.lo
  CC       exefiles.lo
  CC       filemap.lo
  CC       hash.lo
  CC       hex_grammar.lo
  CC       hex_lexer.lo
  CC       lexer.lo
  CC       libyara.lo
  CC       mem.lo
  CC       modules.lo
  CC       object.lo
  CC       parser.lo
  CC       proc.lo
  CC       re.lo
  CC       re_grammar.lo
  CC       re_lexer.lo
  CC       rules.lo
  CC       scan.lo
  CC       scanner.lo
  CC       sizedstr.lo
  CC       stack.lo
  CC       stopwatch.lo
  CC       strutils.lo
  CC       stream.lo
  CC       threading.lo
  CC       modules/tests.lo
  CC       modules/pe.lo
  CC       modules/elf.lo
  CC       modules/math.lo
  CC       modules/time.lo
  CC       modules/pe_utils.lo
  CC       modules/macho.lo
  CC       proc/linux.lo
  CCLD     libyara.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       args.o
  CC       threading.o
  CC       yara.o
  CC       yarac.o
  CCLD     yarac
  CCLD     yara
[ 50%] No install step for 'yara'
[ 56%] Completed 'yara'
[ 56%] Built target yara
Scanning dependencies of target yaracpp
[ 62%] Building CXX object src/CMakeFiles/yaracpp.dir/types/yara_rule.cpp.o
[ 75%] Building CXX object src/CMakeFiles/yaracpp.dir/yara_detector/yara_detector.cpp.o
[ 75%] Building CXX object src/CMakeFiles/yaracpp.dir/types/yara_match.cpp.o
[ 81%] Building CXX object src/CMakeFiles/yaracpp.dir/types/yara_meta.cpp.o
c++: error: yaracpp/main.cpp: No such file or directory
c++: error: yaracpp/main.cpp: No such file or directory
c++: error: yaracpp/main.cpp: No such file or directory
src/CMakeFiles/yaracpp.dir/build.make:110: recipe for target 'src/CMakeFiles/yaracpp.dir/types/yara_rule.cpp.o' failed
make[2]: *** [src/CMakeFiles/yaracpp.dir/types/yara_rule.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/CMakeFiles/yaracpp.dir/build.make:62: recipe for target 'src/CMakeFiles/yaracpp.dir/types/yara_match.cpp.o' failed
make[2]: *** [src/CMakeFiles/yaracpp.dir/types/yara_match.cpp.o] Error 1
src/CMakeFiles/yaracpp.dir/build.make:86: recipe for target 'src/CMakeFiles/yaracpp.dir/types/yara_meta.cpp.o' failed
make[2]: *** [src/CMakeFiles/yaracpp.dir/types/yara_meta.cpp.o] Error 1
c++: error: yaracpp/main.cpp: No such file or directory
src/CMakeFiles/yaracpp.dir/build.make:134: recipe for target 'src/CMakeFiles/yaracpp.dir/yara_detector/yara_detector.cpp.o' failed
make[2]: *** [src/CMakeFiles/yaracpp.dir/yara_detector/yara_detector.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'src/CMakeFiles/yaracpp.dir/all' failed
make[1]: *** [src/CMakeFiles/yaracpp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I'm making a mistake in writing the correct CMakeLists.txt I think. I'd really appreciate if you can help me rectify it!

**Comment by ghost** [comment]
@s3rvac  @metthal 
I wasn't sure if this is the right place to be asking this question so I've posted it on stackoverflow on the following link:

https://stackoverflow.com/questions/56642162/build-using-cmake-a-g-command-with-i-l-and-l

I'd really really really appreciate it if you can help me out with it there!
And thanks a ton guys for helping me out with everything till now! :)

**Comment by dexter0810** [comment]
@s3rvac @metthal
I wasn't sure if this is the right place to be asking this question so I've posted it on stackoverflow on the following link:

https://stackoverflow.com/questions/56642162/build-using-cmake-a-g-command-with-i-l-and-l

I'd really really really appreciate it if you can help me out with it there!
And thanks a ton guys for helping me out with everything till now! :)

**Comment by s3rvac** [comment]
Dear Meghna Vasudeva (@dexter0810),

requests for help are best taken when the person who asks shows at least a minimal effort towards solving the issue by themselves and is willing to learn. In the past few days, you have created three issues in this repository (#7, #9, #10), and none of them show us that you want to learn. In all of them, you seem to be trying to do something by randomly putting pieces of code together, and when that does not work, you immediately panic and ask for our attention. Meanwhile, you lack even elementary knowledge of building and running programs under Linux. We are aware that our usage instructions are not the best, and we will definitely have to work on them, so I give you that. Had the issue been directly related to our projects, we would have gladly helped you out. However, seeing that you want to build a program under Linux with CMake and you do not learn anything about that makes us not wanting to help you. So, our suggestion is to first learn about building and running programs on Linux with focus on CMake. There are many resources for that available online. Try to build small examples and learn about every construct or command that you use. Otherwise, you will be never able to build anything by yourself and you will have to always ask other people to fix the problems for you.

To give you an example, consider the current issue (or your [SO question](https://stackoverflow.com/questions/56642162/build-using-cmake-a-g-command-with-i-l-and-l) for that matter). Looking at the output, there is the following line:
```
c++: error: yaracpp/main.cpp: No such file or directory
```
Does the file exist? Looking at your `CMakeLists.txt`, the file appears in the following command:
```
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} [..] yaracpp/main.cpp ")
                                              ^^^^^^^^^^^^^^^^
```
What is the purpose of `CMAKE_CXX_FLAGS`? Should source files be part of `CMAKE_CXX_FLAGS`? Why do you add `yaracpp/main.cpp` into `CMAKE_CXX_FLAGS` when it has already been added in the following line?
```
add_executable(main main.cpp)
                    ^^^^^^^^
```
I highly suggest learning the basics of CMake before continuing in your endeavours.

Also, please do not mindlessly flag me and @metthal in every comment that you make. Members of our team are notified about issues and comments that appear in repositories that we develop, and the most competent (or available) member will deal with them.

I am closing the issue as invalid as it is not directly related to `yaracpp`.

**Comment by ghost** [comment]
Hi, firstly I would like to sincerely apologize for having troubled you all. I understand where you're coming from. I appreciate that you guys took out the time to guide me. 
Thank you for your kind advice, I really don't want this to happen:
Otherwise, you will be never able to build anything by yourself and you will have to always ask other people to fix the problems for you.

Thank you for helping me realize my mistake Sir and I apologize once again for being naive and disturbing you.
