### ISSUE TITLE
yaracpp does not compile from cmake in MSYS2

### ISSUE THREAD

**Issue by twitzelbos** [avast-tl/yaracpp#12]
When compiling the entire retdec package for MSYS2, the yaracpp-project build fails on all my machines with MSYS2.
The error occurs during the configure and looks like aclocal is missing a /c/ in its path:
```
::::::::::::::
C:/Users/witze/git/retdec/build/external/src/yaracpp-project-stamp/yaracpp-project-build-err.log
::::::::::::::
aclocal-1.16: error: aclocal: file '/msys64/usr/share/aclocal/xsize.m4' does not exist
autoreconf: aclocal failed with exit status: 1
make[5]: *** [deps/CMakeFiles/yara.dir/build.make:122: deps/yara/src/yara-stamp/yara-configure-linu
x] Error 1
make[4]: *** [CMakeFiles/Makefile2:91: deps/CMakeFiles/yara.dir/all] Error 2
make[3]: *** [Makefile:84: all] Error 2
```

Strangely, when I go to external/src/yaracpp-project-build and manually "make", everything succeeds just fine... 
So when inside the external/src/yaracpp-project-build folder
```make```
succeeds and 
```cmake --build . --config Release -- -m```
fails during configure.

If I manually specify the aclocal path first with
```export ACLOCAL_PATH="/c/msys64/usr/share/aclocal/"```
then the cmake command succeeds.

I have seen the same configure error happening in other projects on msys2 via google, but no resolution. I'm stumped here as to where this needs to be fixed.

**Comment by s3rvac** [comment]
OK. Now, based on the output you have provided, the build seems to fail when configuring yara, which is a dependency of yaracpp. Could you please try building just yara by following the steps below?
```
git clone https://github.com/avast/yara.git -b retdec
cd yara
./bootstrap.sh
./configure
make
```
Should any of the steps fail, please let us know which one and provide its output.

**Comment by twitzelbos** [comment]
None of these steps fail. I did not expect them to, because the failure is somehow created by cmake messing up the ACLOCAL_PATH and cmake isn't involved in your steps.

**Comment by s3rvac** [comment]
Thank you for verification. Let me see if I can reproduce this on my Windows installation (I do not have it at hand right now but I will be able to try it in the beginning of next week).

**Comment by s3rvac** [comment]
I was able to successfully build yaracpp in an up-to-date MSYS2 installation on the following two systems:
* 32b Windows 7 
* 64b Windows Server 2012 R2

Steps:
```
$ git clone https://github.com/avast/yaracpp
$ cd yaracpp
$ mkdir build
$ cd build
$ cmake .. -G"MSYS Makefiles"
$ cmake --build . --config Release -- -m
```
So, it seems that there is something specific to your environment or to the steps you have taken to build yaracpp.

I have also tried to search for this issue online, but have not found any solution either. I am afraid that you will either have to debug this by yourself or we will have to wait until there is someone else having the same issue.

**Comment by twitzelbos** [comment]
Hello Petr,
Thank you for looking into this issue.
The same steps fail on all my systems, including a new setup msys2 environment. I suppose the only difference between us is now that all my systems are Windows 10 64bit.
The workaround is pretty straightforward, as all you have to do is to define in your environment
```export ACLOCAL_PATH="/c/msys64/usr/share/aclocal/"```
and it all works just fine.

**Comment by s3rvac** [comment]
I see. Well, the silver lining is that there is at least a workaround. Let's keep the issue open for now. Maybe someone else will stumble upon it and be able to shed some light on why is this happening.

**Comment by twitzelbos** [comment]
I really wanted to ask the msys2 person who chimed in on my issue606 patch, but it appears that all his comments disappeared, so I can no longer find his name.

Thomas

**Comment by s3rvac** [comment]
His profile is [here](https://github.com/Alexpux).

**Comment by s3rvac** [comment]
We have moved the discussion to https://github.com/avast/retdec/issues/692 as we have archived the `avast/yaracpp` repository (the code has been integrated to RetDec).
