### ISSUE TITLE
Compilation fails with "error: ‘decay_t’ is not a member of ‘std’"

### ISSUE THREAD

**Issue by lilei-John** [avast-tl/yaracpp#3]
yara_detector.cpp:55:17: error: ‘decay_t’ is not a member of ‘std’

**Comment by s3rvac** [comment]
Hi. What compiler do you use? It seems to me that you use GCC 4.8, which does not support `std::decay_t`. You will need at least GCC 4.9.

@metthal Maybe we should mention the minimal GCC version in the README?

**Comment by metthal** [comment]
As @s3rvac said, can you please provide us more information about your compiler and system?

@s3rvac: `README` says that you need the compiler with C++14 support, but I can explicitly mention the minimal version of GCC. If 4.9 is the first version that supports C++14 I can add it there.

**Comment by lilei-John** [comment]
It's been compiled, thank you very much.

**Comment by s3rvac** [comment]
> README says that you need the compiler with C++14 support, but I can explicitly mention the minimal version of GCC. If 4.9 is the first version that supports C++14 I can add it there.

I would do that. BTW, technically, the first GCC version that has full support for C++14 is 5 ([ref](https://en.cppreference.com/w/cpp/compiler_support#cpp14)), but I believe that `yaracpp` requires only the part of C++14 that is already available in GCC 4.9. The situation is similar with Visual Studio (for full C++14 support, one needs VS 2017, but `yaracpp` can be compiled just fine with VS 2015).
