### ISSUE TITLE
Build error due to executing linux command on windows

### ISSUE THREAD

**Issue by Lakasabasz** [avast-tl/yaracpp#4]
I'm using GCC (v 7.2.0) on Windows. After building project with cmake (without any errors) I tried to compile it, but appears error:
`[ 42%] Performing configure-linux step for 'yara'
cd /d G:\sync\yaracpp-master\deps\yara\src\yara && .\bootstrap.sh
mingw32-make.exe[2]: *** [deps\CMakeFiles\yara.dir\build.make:120: deps/yara/src/yara-stamp/yara-configure-linux] Error -1073741819
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:85: deps/CMakeFiles/yara.dir/all] Error 2
mingw32-make.exe: *** [G:/sync/yaracpp-master/Makefile:83: all] Error 2`

All of build log:
[log.txt](https://github.com/avast-tl/yaracpp/files/2245153/log.txt)

My question is what is the task of file bootstarp.sh, and can I skip it?

**Comment by metthal** [comment]
I just tested build of `yaracpp` in MinGW environment and it should be fine. Make sure you have autotools installed in your system (`autoconf`, `automake`, ...).

**Comment by Lakasabasz** [comment]
Key in register which runs shell was wrong. Now is better, but I have still error:
Log from manually started bootstarp.sh:
```
HP@HP-Komputer MSYS /g/sync/yaracpp-master/deps/yara/src/yara
$ automake --version
automake (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

HP@HP-Komputer MSYS /g/sync/yaracpp-master/deps/yara/src/yara
$ ./bootstrap.sh
configure.ac:29: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by s3rvac** [comment]
I think this is the same error as in https://github.com/avast-tl/retdec/issues/25#issuecomment-351732477. You will need to install `libtool`. We have included this dependency into the README (d57ecfcb09b78dec9cba4ed15038a5528a8a728a).

**Comment by s3rvac** [comment]
@Lakasabasz I just want to ask, has the installation of `libtool` fixed the problem for you?

**Comment by s3rvac** [comment]
I am closing this as we have not received any feedback in the last three weeks. Feel free to reopen if the above solution does not work for you.
