### ISSUE TITLE
How to include yaracpp to another project

### ISSUE THREAD

**Issue by Miracle-doctor** [avast-tl/yaracpp#6]

**Comment by metthal** [comment]
There are many options:

1. [ExternalProject](https://cmake.org/cmake/help/latest/module/ExternalProject.html) if you are using CMake.
2. [Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) if you are using CMake and git.
3. Prebuilt libraries if you are using Windows and you don't want to worry about compilation.
...

I am sure there are also some other options but there are the ones I came up with of the top of my head.
