### ISSUE TITLE
Windows installation issue

### ISSUE THREAD

**Issue by ghost** [avast-tl/yaracpp#7]
I've installed the following: 
- GCC Version:  6.3.0
- Visual Studio 2019
- cmake version 3.15.0-rc1
- Have autoconf, automake and libtool files inside bin folder of MinGW.

When I run the command: 
cmake -G"Visual Studio 16 2019 Win64"
I get:
CMake Error: Could not create named generator Visual Studio 16 2019 Win64

When I run: 
cmake --build . --config Release -- -m
I get:
CMake Error:
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.

Any help will be appreciated. :)

**Comment by metthal** [comment]
Just to be sure, do you want to build using Visual Studio or MinGW toolchain? Because you mentioned that you have GCC, autotools and libtool installed but then you tried to use Visual Studio generator. I will presume that you wanted to use Visual Studio.

I would probably make sure that your CMake and Visual Studio are installed correctly. Try to reinstall Visual Studio or even both VS and CMake. It seems like your CMake can't find the installation of VS for some reason.

**Comment by ghost** [comment]
I tried installing both again, same errors :( 

Any way I can try with the CMake Gui to get it working?

**Comment by metthal** [comment]
You can try that. Also make sure that cmake you are running is the one you mentioned in the first post (3.15). `Visual Studio 16 2019` is generator supported since 3.14 so make sure that you are not running some other cmake installed from other bundle.

**Comment by dexter0810** [comment]
Hi :) 
After running via cmake gui. my build folder got populated with:
- CMakeFiles (File folder)
- deps (File folder)
- src(File folder)
- CMakeCache (Text Document)


I couldn't find the yaracpp.sln file anywhere :( 


These were the messages shown in CMake GUI: 

Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
The CXX compiler identification is MSVC 19.21.27702.2
The C compiler identification is MSVC 19.21.27702.2
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Configuring done


Can you please tell me how I can get the example usage program running successfully after this point? 
Thanks so much for taking the time to help me out, I really appreciate it :)

**Comment by ghost** [comment]
After using CMake GUI I was able to generate yaracpp.sln file. :D
Can you please tell me how to proceed further so as to implement the usage example program successfully? 
Thanks for taking the time to help me out, I really appreciate it :)

**Comment by ghost** [comment]
I opened yaracpp.sln in Visual Studio and then I added the example usage program in main.cpp and added that as an item in source files. I build on the ALL_BUILD folder which gets done successfully and when I click on local windows debugger it shows me the prompt:
"Unable to start program
'C:\Users\t-mevasu\yaracpp\build\x64\Release\ALL_BUILD'.
Access is denied."
