### ISSUE TITLE
How to run example usage program successfully in Ubuntu after building

### ISSUE THREAD

**Issue by ghost** [avast-tl/yaracpp#8]
After building as per the commands in : https://github.com/avast/yaracpp/blob/master/.travis.yml. 

How can I get the following program to run successfully:

#include <iostream>
#include "yaracpp/yaracpp.h"

int main() {
    yaracpp::YaraDetector yara;
    yara.addRules(R"(
        rule example {
            strings:
                $s = "Hello"
            condition:
                $s
        })");
    yara.addRuleFile("/path/to/yara_file.yar");

    if (yara.analyze("/path/to/scanned/file")) {
        for (const auto& rule : yara.getDetectedRules()) {
            std::cout << rule << '\n';
        }
    }
}

I'm using Ubuntu 18.04. 
I'm new to this and would really appreciate any help :) 
Thank you!

**Comment by metthal** [comment]
At first, you need to tell us what is not working. What kind of error message do you get?

**Comment by ghost** [comment]
In Ubuntu I just ran the commands:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="$(pwd)/install" ..
  - cmake --build . -- -j $NPROC

 This is what showed up in terminal after the latest command:

**~/yaracpp/build$ cmake --build . -- -j $NPROC**
Scanning dependencies of target yara
[  7%] Creating directories for 'yara'
[ 14%] Performing download step (download, verify and extract) for 'yara'
-- Downloading...
   dst='/home/mevasu/yaracpp/build/deps/yara/src/yara.zip'
   timeout='none'
-- Using src='https://github.com/avast/yara/archive/e3ae3848d66cdb551e149f1a87a45bcc87578f9c.zip'
-- verifying file...
       file='/home/mevasu/yaracpp/build/deps/yara/src/yara.zip'
-- Downloading... done
-- extracting...
     src='/home/mevasu/yaracpp/build/deps/yara/src/yara.zip'
     dst='/home/mevasu/yaracpp/build/deps/yara/src/yara'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 21%] No update step for 'yara'
[ 28%] No patch step for 'yara'
[ 35%] No configure step for 'yara'
[ 42%] Performing configure-linux step for 'yara'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:20: installing 'build-aux/ar-lib'
configure.ac:20: installing 'build-aux/compile'
configure.ac:28: installing 'build-aux/config.guess'
configure.ac:28: installing 'build-aux/config.sub'
configure.ac:8: installing 'build-aux/install-sh'
configure.ac:8: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
configure.ac: installing 'build-aux/ylwrap'
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... /usr/bin/cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/cc accepts -g... yes
checking for /usr/bin/cc option to accept ISO C89... none needed
checking whether /usr/bin/cc understands -c and -o together... yes
checking dependency style of /usr/bin/cc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for gcc... (cached) /usr/bin/cc
checking whether we are using the GNU C compiler... (cached) yes
checking whether /usr/bin/cc accepts -g... (cached) yes
checking for /usr/bin/cc option to accept ISO C89... (cached) none needed
checking whether /usr/bin/cc understands -c and -o together... (cached) yes
checking dependency style of /usr/bin/cc... (cached) gcc3
checking for flex... no
checking for lex... no
checking for bison... no
checking for byacc... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by /usr/bin/cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from /usr/bin/cc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... /usr/bin/cc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /usr/bin/cc supports -fno-rtti -fno-exceptions... no
checking for /usr/bin/cc option to produce PIC... -fPIC -DPIC
checking if /usr/bin/cc PIC flag -fPIC -DPIC works... yes
checking if /usr/bin/cc static flag -static works... yes
checking if /usr/bin/cc supports -c -o file.o... yes
checking if /usr/bin/cc supports -c -o file.o... (cached) yes
checking whether the /usr/bin/cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking whether byte ordering is bigendian... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking whether to check for GCC pthread/shared inconsistencies... yes
checking whether -pthread is sufficient with -shared... yes
checking for isnan in -lm... yes
checking for log2 in -lm... yes
checking for strlcpy... no
checking for strlcat... no
checking for memmem... yes
checking for timegm... yes
checking for _mkgmtime... no
configure: WARNING:

*****************************************************************
  Could not find OpenSSL library. Some features in "pe" module
  have been disabled. If you want to enable all features please
  install OpenSSL and run this script again.
*****************************************************************

checking for Microsoft Crypto API... checking for wincrypt.h... no
checking for MacOSX Common Crypto API... checking CommonCrypto/CommonCrypto.h usability... no
checking CommonCrypto/CommonCrypto.h presence... no
checking for CommonCrypto/CommonCrypto.h... no
configure: WARNING:

*****************************************************************
  Could not find alternative APIs for hash functions. The "hash"
  module has been disabled.
*****************************************************************
            
checking stdbool.h usability... yes
checking stdbool.h presence... yes
checking for stdbool.h... yes
checking for clock_gettime... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libyara/Makefile
config.status: creating libyara/yara.pc
config.status: executing depfiles commands
config.status: executing libtool commands
[ 50%] Performing build step for 'yara'
Making all in libyara
  CC       ahocorasick.lo
  CC       atoms.lo
  CC       arena.lo
  CC       grammar.lo
  CC       bitmask.lo
  CC       compiler.lo
  CC       endian.lo
  CC       exec.lo
  CC       exefiles.lo
  CC       filemap.lo
  CC       hash.lo
  CC       hex_grammar.lo
  CC       hex_lexer.lo
  CC       lexer.lo
  CC       libyara.lo
  CC       mem.lo
  CC       modules.lo
  CC       object.lo
  CC       parser.lo
  CC       proc.lo
  CC       re.lo
  CC       re_grammar.lo
  CC       re_lexer.lo
  CC       rules.lo
  CC       scan.lo
  CC       scanner.lo
  CC       sizedstr.lo
  CC       stack.lo
  CC       stopwatch.lo
  CC       strutils.lo
  CC       stream.lo
  CC       threading.lo
  CC       modules/tests.lo
  CC       modules/pe.lo
  CC       modules/elf.lo
  CC       modules/math.lo
  CC       modules/time.lo
  CC       modules/pe_utils.lo
  CC       modules/macho.lo
  CC       proc/linux.lo
  CCLD     libyara.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       args.o
  CC       threading.o
  CC       yara.o
  CC       yarac.o
  CCLD     yarac
  CCLD     yara
[ 57%] No install step for 'yara'
[ 64%] Completed 'yara'
[ 64%] Built target yara
Scanning dependencies of target yaracpp
[ 71%] Building CXX object src/CMakeFiles/yaracpp.dir/types/yara_meta.cpp.o
[ 78%] Building CXX object src/CMakeFiles/yaracpp.dir/types/yara_match.cpp.o
[ 85%] Building CXX object src/CMakeFiles/yaracpp.dir/types/yara_rule.cpp.o
[ 92%] Building CXX object src/CMakeFiles/yaracpp.dir/yara_detector/yara_detector.cpp.o
[100%] Linking CXX static library libyaracpp.a
[100%] Built target yaracpp












Then my build folder got populated with:

-CMakeFiles (folder)
-deps (folder)
-src (folder)
-CMakeCache.txt
-cmake_install.cmake
-Makefile

Is this how it should look?
I don't know how to proceed further.

**Comment by ghost** [comment]
@metthal  I've posted the problem when I'm working on Windows 10 in the previous issue. 
:)

**Comment by ghost** [comment]
@metthal  @s3rvac 
I created main.cpp(example usage program) and saved it inside the include folder in yaracpp.  I got this error:

In file included from main.cpp:2:0:
yaracpp/yaracpp.h:10:10: fatal error: yaracpp/yara_detector/yara_detector.h: No such file or directory
 #include "yaracpp/yara_detector/yara_detector.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I thought changing the contents of header files wouldn't be the right way. 
Had another train of thought to change CMakeLists.txt by adding: add_executable(), but wasn't sure what arguments should be passed and which library to link it with exactly? Feeling a little lost here.

Can you please guide me how to get the program to run successfully? I'd really appreciate any help :)

**Comment by metthal** [comment]
`yaracpp` is built into static library `libyaracpp.a`. You need to take this library + `include` folder and make sure that the application you are trying to build can find the `include` directory `libyaracpp.a` is linked against this library. It will look like this: `g++ -Iinclude -Lbuild/src/ -Lbuild/deps/yara/src/yara/libyara/.libs/ <source_file.cpp> -lyaracpp -lyara`.

Alternatively, you can help write [install](https://cmake.org/cmake/help/v3.15/command/install.html) targets for `yaracpp` which would make it easier for you to integrate this project into yours but this will be more difficult.

**Comment by ghost** [comment]
I understand. 
Inside build/deps/yara/src/yara/libyara I don't have a .libs folder :( 

Inside build/deps/yara/src/yara/libyara I have: 
include
modules
proc
And many .c, .o, .lo, .h and .y files only
:(

**Comment by metthal** [comment]
Are you sure? What do you use to inspect the contents of that directory? If `ls` then make sure to use `ls -a` to also include files and directories that start with dot.

**Comment by ghost** [comment]
Ah, my bad. I did not know that.
I do see a .libs folder now when I do ls -a.


This is happening when I run the following command:
~/yaracpp$ g++ -Iinclude -Lbuild/src/ -Lbuild/deps/yara/src/yara/libyara/.libs/ main.cpp -lyaracpp -lyara
build/deps/yara/src/yara/libyara/.libs//libyara.a(threading.o): In function `yr_thread_storage_create':
threading.c:(.text+0x97): undefined reference to `pthread_key_create'
build/deps/yara/src/yara/libyara/.libs//libyara.a(threading.o): In function `yr_thread_storage_destroy':
threading.c:(.text+0xb7): undefined reference to `pthread_key_delete'
build/deps/yara/src/yara/libyara/.libs//libyara.a(threading.o): In function `yr_thread_storage_set_value':
threading.c:(.text+0xd7): undefined reference to `pthread_setspecific'
build/deps/yara/src/yara/libyara/.libs//libyara.a(threading.o): In function `yr_thread_storage_get_value':
threading.c:(.text+0xf3): undefined reference to `pthread_getspecific'
collect2: error: ld returned 1 exit status

**Comment by metthal** [comment]
Also add `-lpthread` at the very end.

**Comment by ghost** [comment]
this is my main.cpp:
#include <iostream>
#include "yaracpp/yaracpp.h"

int main() {
    yaracpp::YaraDetector yara;
    yara.addRules(R"(
        rule example {
            strings:
                $s = "Hello"
            condition:
                $s
        })");
    //yara.addRuleFile("/path/to/yara_file.yar");
      yara.addRuleFile("test_file");	

    if (yara.analyze("test_file")) {
        for (const auto& rule : yara.getDetectedRules()) {
            std::cout << rule << '\n';
        }
    }
}


this is test_file:
Hello byee

After running:
g++ -Iinclude -Lbuild/src/ -Lbuild/deps/yara/src/yara/libyara/.libs/ main.cpp -lyaracpp -lyara -lpthread

It should show me example main.cpp right?

It doesn't show me anything :(

test_file and main.cpp are both inside yaracpp folder

**Comment by metthal** [comment]
My bad, I forgot about yara includes, try this:

`g++ -Iinclude -Ibuild/deps/yara/src/yara/libyara/include/ -Lbuild/src/ -Lbuild/deps/yara/src/yara/libyara/.libs/ main.cpp -lyaracpp -lyara -lpthread`

Also your `test_file` is not valid YARA rule file so it won't show you anything in your case. You need to create at least one YARA rule in it.

**Comment by ghost** [comment]
main.cpp:
#include <iostream>
#include "yaracpp/yaracpp.h"

int main() {
    yaracpp::YaraDetector yara;
    yara.addRules(R"(
        rule example {
            strings:
                $s = "Hello"
            condition:
                $s
        })");
    //yara.addRuleFile("/path/to/yara_file.yar");
      yara.addRuleFile("rule_file");	

    if (yara.analyze("test_file")) {
        for (const auto& rule : yara.getDetectedRules()) {
            std::cout << rule << '\n';
        }
    }
}


rule_file:
rule example {
            strings:
                $s = "Hello"
            condition:
                $s
        }

test_file:
Hello byee


g++ -Iinclude -Ibuild/deps/yara/src/yara/libyara/include/ -Lbuild/src/ -Lbuild/deps/yara/src/yara/libyara/.libs/ main.cpp -lyaracpp -lyara -lpthread


Still nada :(

**Comment by s3rvac** [comment]
Just to be sure, have you actually run the program? Via
```
./a.out
```
It should print `example`.

**Comment by ghost** [comment]
Yes I did :(

**Comment by ghost** [comment]
#include <iostream>
#include "yaracpp/yaracpp.h"

int main() {
    yaracpp::YaraDetector yara;
    yara.addRules(R"(
        rule example {
            strings:
                $s = "Hello"
            condition:
                $s
        })");
    //yara.addRuleFile("/path/to/yara_file.yar");
      //yara.addRuleFile("rule_file");	

    if (yara.analyze("test_file")) {
        for (const auto& rule : yara.getDetectedRules()) {
            std::cout << rule << '\n';
        }
    }
}

When this is my main.cpp, ./a.out shows me example but when my main.cpp is:
#include <iostream>
#include "yaracpp/yaracpp.h"

int main() {
    yaracpp::YaraDetector yara;
    yara.addRules(R"(
        rule example {
            strings:
                $s = "Hello"
            condition:
                $s
        })");
    //yara.addRuleFile("/path/to/yara_file.yar");
      yara.addRuleFile("rule_file");	

    if (yara.analyze("test_file")) {
        for (const auto& rule : yara.getDetectedRules()) {
            std::cout << rule << '\n';
        }
    }
}

then ./a.out shows:
./a.out
a.out: compiler.c:825: yr_compiler_get_rules: Assertion `compiler->errors == 0' failed.
Aborted (core dumped)

**Comment by s3rvac** [comment]
The issue is that you have two rules having the same name (one in `main.cpp` and one in `rule_file`). You need to either use only one of these rules or change the name of one of them.

**Comment by ghost** [comment]
Ah, alright. 
Thanks a lot @metthal  @s3rvac  for helping me out and clarifying my silly doubts too. 
I really appreciate it! :)
