### ISSUE TITLE
Add option to build yara with crypto support

### ISSUE THREAD

**Issue by ghost** [avast-tl/yaracpp#9]
Hi again :P 

So when I was building the library, I got the following response after this command:

 **cmake --build . -- -j $NPROC**
Scanning dependencies of target yara
[  7%] Creating directories for 'yara'
[ 14%] Performing download step (download, verify and extract) for 'yara'
-- Downloading...
   dst='/home/mevasu/Desktop/yaracpp/build/deps/yara/src/yara.zip'
   timeout='none'
-- Using src='https://github.com/avast/yara/archive/e3ae3848d66cdb551e149f1a87a45bcc87578f9c.zip'
-- verifying file...
       file='/home/mevasu/Desktop/yaracpp/build/deps/yara/src/yara.zip'
-- Downloading... done
-- extracting...
     src='/home/mevasu/Desktop/yaracpp/build/deps/yara/src/yara.zip'
     dst='/home/mevasu/Desktop/yaracpp/build/deps/yara/src/yara'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 28%] No update step for 'yara'
[ 28%] No patch step for 'yara'
[ 35%] No configure step for 'yara'
[ 42%] Performing configure-linux step for 'yara'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:20: installing 'build-aux/ar-lib'
configure.ac:20: installing 'build-aux/compile'
configure.ac:28: installing 'build-aux/config.guess'
configure.ac:28: installing 'build-aux/config.sub'
configure.ac:8: installing 'build-aux/install-sh'
configure.ac:8: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
configure.ac: installing 'build-aux/ylwrap'
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... /usr/bin/cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/cc accepts -g... yes
checking for /usr/bin/cc option to accept ISO C89... none needed
checking whether /usr/bin/cc understands -c and -o together... yes
checking dependency style of /usr/bin/cc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for gcc... (cached) /usr/bin/cc
checking whether we are using the GNU C compiler... (cached) yes
checking whether /usr/bin/cc accepts -g... (cached) yes
checking for /usr/bin/cc option to accept ISO C89... (cached) none needed
checking whether /usr/bin/cc understands -c and -o together... (cached) yes
checking dependency style of /usr/bin/cc... (cached) gcc3
checking for flex... no
checking for lex... no
checking for bison... no
checking for byacc... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by /usr/bin/cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from /usr/bin/cc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... /usr/bin/cc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /usr/bin/cc supports -fno-rtti -fno-exceptions... no
checking for /usr/bin/cc option to produce PIC... -fPIC -DPIC
checking if /usr/bin/cc PIC flag -fPIC -DPIC works... yes
checking if /usr/bin/cc static flag -static works... yes
checking if /usr/bin/cc supports -c -o file.o... yes
checking if /usr/bin/cc supports -c -o file.o... (cached) yes
checking whether the /usr/bin/cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking whether byte ordering is bigendian... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking whether to check for GCC pthread/shared inconsistencies... yes
checking whether -pthread is sufficient with -shared... yes
checking for isnan in -lm... yes
checking for log2 in -lm... yes
checking for strlcpy... no
checking for strlcat... no
checking for memmem... yes
checking for timegm... yes
checking for _mkgmtime... no
configure: WARNING:

*****************************************************************
  Could not find OpenSSL library. Some features in "pe" module
  have been disabled. If you want to enable all features please
  install OpenSSL and run this script again.
*****************************************************************

checking for Microsoft Crypto API... checking for wincrypt.h... no
checking for MacOSX Common Crypto API... checking CommonCrypto/CommonCrypto.h usability... no
checking CommonCrypto/CommonCrypto.h presence... no
checking for CommonCrypto/CommonCrypto.h... no
configure: WARNING:

*****************************************************************
  Could not find alternative APIs for hash functions. The "hash"
  module has been disabled.
*****************************************************************
            
checking stdbool.h usability... yes
checking stdbool.h presence... yes
checking for stdbool.h... yes
checking for clock_gettime... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libyara/Makefile
config.status: creating libyara/yara.pc
config.status: executing depfiles commands
config.status: executing libtool commands
[ 50%] Performing build step for 'yara'
Making all in libyara
  CC       ahocorasick.lo
  CC       arena.lo
  CC       grammar.lo
  CC       bitmask.lo
  CC       atoms.lo
  CC       compiler.lo
  CC       endian.lo
  CC       exec.lo
  CC       exefiles.lo
  CC       filemap.lo
  CC       hash.lo
  CC       hex_grammar.lo
  CC       hex_lexer.lo
  CC       lexer.lo
  CC       libyara.lo
  CC       mem.lo
  CC       modules.lo
  CC       object.lo
  CC       parser.lo
  CC       proc.lo
  CC       re.lo
  CC       re_grammar.lo
  CC       re_lexer.lo
  CC       rules.lo
  CC       scan.lo
  CC       scanner.lo
  CC       sizedstr.lo
  CC       stack.lo
  CC       stopwatch.lo
  CC       strutils.lo
  CC       stream.lo
  CC       threading.lo
  CC       modules/tests.lo
  CC       modules/pe.lo
  CC       modules/elf.lo
  CC       modules/math.lo
  CC       modules/time.lo
  CC       modules/pe_utils.lo
  CC       modules/macho.lo
  CC       proc/linux.lo
  CCLD     libyara.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       args.o
  CC       threading.o
  CC       yarac.o
  CC       yara.o
  CCLD     yarac
  CCLD     yara
[ 57%] No install step for 'yara'
[ 64%] Completed 'yara'
[ 64%] Built target yara
Scanning dependencies of target yaracpp
[ 71%] Building CXX object src/CMakeFiles/yaracpp.dir/types/yara_meta.cpp.o
[ 85%] Building CXX object src/CMakeFiles/yaracpp.dir/yara_detector/yara_detector.cpp.o
[ 85%] Building CXX object src/CMakeFiles/yaracpp.dir/types/yara_match.cpp.o
[ 92%] Building CXX object src/CMakeFiles/yaracpp.dir/types/yara_rule.cpp.o
[100%] Linking CXX static library libyaracpp.a
[100%] Built target yaracpp

Hence, when I imported the hash module in my rule it didn't show me the expected output. 

I tried the following to resolve it: 
1. Built using CMake GUI and then tested the hash rule, same issue arose. 
2. Installed OpenSSL, got OpenSSL 1.1.1 version, tried building again after emptying the build folder. Same issue. :(  

Any leads will be appreciated. :)

**Comment by metthal** [comment]
Make sure to install development version of OpenSSL package. I think you've mentioned earlier that you are running Ubuntu. In that case that would be `libssl-dev`.

**Comment by ghost** [comment]
Ran this:
sudo apt install libssl1.0-dev
(Reference: https://serverfault.com/questions/249340/install-openssl-dev-on-ubuntu-server )

Same issue persists :(

**Comment by ghost** [comment]
@metthal  @s3rvac 

As per : https://buildmedia.readthedocs.org/media/pdf/yara/v3.6.0/yara.pdf
I tried running ./configure --with-crypto and then sudo apt-get install libssl-dev inside yaracpp/build/deps/yara/src/yara. When I type openssl version it shows me OpenSSL 1.1.1  11 Sep 2018.


In the same folder I opened terminal and I ran **yara rule_file sieve.apk**
where rule_file is:

import "hash"
rule test_rule {
condition:
 hash.sha256(0, filesize)=="31878e33c526f9747c9b7ff38954bfcb2acc2a947ce7103589438e034637a6b7"
}

sieve.apk can be downloaded from: 
https://github.com/as0ler/Android-Examples/blob/master/sieve.apk

When I ran **yara rule_file sieve.apk** in Ubuntu I got: 
rule_file(1): error: unknown module "hash"
rule_file(4): error: invalid field name "sha256"

Am I running the ./configure--with-crypto and sudo apt-get install libssl-dev in the wrong place? 
What should I do to enable the hash module? Any help is greatly appreciated. :)

**Comment by metthal** [comment]
I just realized that we are actually building YARA without crypto because we don't need it for our usecases. Until we add support for it, please modify `deps/CMakeLists.txt` and remove `-without-crypto` line. You might also need to add `-lssl -lcrypto` as your linker flags.

**Comment by metthal** [comment]
I have renamed your ticket to better match what is desired.

**Comment by ghost** [comment]
@metthal AFter removing the --without-crypto line should I replace it with -lssl -lcrypto then the hash module will work? 

I also tried this after ./configure--with-crypto command an openssl folder got installed in my yara-3.3.0 folder, so I pasted it's grandparent (windows/include/openssl) inside build folder and added this -Iwindows/include but that didn't work either :(

Final command: g++ -Iinclude -Ibuild/deps/yara/src/yara/libyara/include -Lbuild/deps/yara/src/yara/libyara/libs/main.cpp -lyaracpp -lyara -lpthread

**Comment by metthal** [comment]
No, just remove `--without-crypto` from `deps/CMakeLists.txt` and when compiling your own program run this

```
g++ -Iinclude -Ibuild/deps/yara/src/yara/libyara/include -Lbuild/deps/yara/src/yara/libyara/libs/ main.cpp -lyaracpp -lyara -lpthread -lssl -lcrypto
```

**Comment by ghost** [comment]
@metthal Did exactly what you mentioned but the rules with the hash module still don't work :(

**Comment by ghost** [comment]
@metthal  Since this doesn't seem to work I was wondering if there is a way to test the hash of a file without using the hash module? Only by using strings?

**Comment by metthal** [comment]
It doesn't help me whatsoever if you just simply say that it doesn't work. Always provide logs of what it prints out.

**Comment by dexter0810** [comment]
I'm sorry I'll be careful now onwards :) 

In this case it doesn't show any errors or any response. The problem is it should have printed the rule name but it doesn't print anything at all. 

For example: 
main.cpp is:

#include <iostream>
#include "yaracpp/yaracpp.h"

int main() {
yaracpp::YaraDetector yara;
yara.addRules(R"(
rule example {
strings:
$s = "Hello"
condition:
$s
})");

if (yara.analyze("test_file")) {
    for (const auto& rule : yara.getDetectedRules()) {
        std::cout << rule << '\n';
    }
}
}


test_file is:
Hello Bye bye
and 

 ./a.out shows:
example

BUT
when my main.cpp is:

**Comment by dexter0810** [comment]
@metthal  I'm sorry, I'll be vareful now onwards :) 

mevasu@mevasu-Virtual-Machine:~/yaracpp$ **g++ -Iinclude -Ibuild/deps/yara/src/yara/libyara/include/ -Lbuild/src/ -Lbuild/deps/yara/src/yara/libyara/.libs/ main.cpp -lyaracpp -lyara -lpthread -lssl -lcrypto**
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status

**Comment by ghost** [comment]
@metthal  I'm sorry, I'll be careful now onwards :) 
When main.cpp is:
#include <iostream>
#include "yaracpp/yaracpp.h"

int main() {
    yaracpp::YaraDetector yara;
    yara.addRules(R"(
        rule example {
            strings:
                $s = "Hello"
            condition:
                $s
        })");
    //yara.addRuleFile("/path/to/yara_file.yar");

    if (yara.analyze("test_file")) {
        for (const auto& rule : yara.getDetectedRules()) {
            std::cout << rule << '\n';
        }
    }
}
and where test_file is:
Hello Bye bye

This happens:
 g++ -Iinclude -Ibuild/deps/yara/src/yara/libyara/include/ -Lbuild/src/ -Lbuild/deps/yara/src/yara/libyara/.libs/ main.cpp -lyaracpp -lyara -lpthread -lssl -lcrypto
mevasu@mevasu-Virtual-Machine:~/yaracpp$ ./a.out
example

But when main.cpp is: 
#include <iostream>
#include "yaracpp/yaracpp.h"

int main() {
    yaracpp::YaraDetector yara;
    yara.addRules(R"(
	***import "hash"***
        rule example {
            strings:
                $s = "Hello"
            condition:
                $s
        })");
    //yara.addRuleFile("/path/to/yara_file.yar");

    if (yara.analyze("test_file")) {
        for (const auto& rule : yara.getDetectedRules()) {
            std::cout << rule << '\n';
        }
    }
}

This happens:
g++ -Iinclude -Ibuild/deps/yara/src/yara/libyara/include/ -Lbuild/src/ -Lbuild/deps/yara/src/yara/libyara/.libs/ main.cpp -lyaracpp -lyara -lpthread -lssl -lcrypto
mevasu@mevasu-Virtual-Machine:~/yaracpp$ ./a.out


It doesn't show anything at all :(

**Comment by metthal** [comment]
Just follow these steps:

1. Remove all files related to your previous build (aka `build` folder)
2. Remove `--without-crypto` from `deps/CMakeLists.txt`
3. Build `yaracpp`
4. Compile your program `g++ -Iinclude -Ibuild/deps/yara/src/yara/libyara/include/ -Lbuild/src/ -Lbuild/deps/yara/src/yara/libyara/.libs/ main.cpp -lyaracpp -lyara -lpthread -lssl -lcrypto`
5. Run it `./a.out`

It should print out `example` if the file you are scanning contains `Hello`. I've tested it multiple times and it works. Before you reply again that it _doesn't work_ try to reevaluate what you are doing. Try to check if your OpenSSL installation is working. Check build log if there is any error there.

One more post that it _doesn't work_ without providing detailed description won't help you nor me.

**Comment by metthal** [comment]
Reopening the issue since the original claim is still valid. We don't have an option to build with crypto support and we should add it.

**Comment by s3rvac** [comment]
Closing as this is out of any of our use cases. Also, we have archived the `avast/yaracpp` repository (it has been integrated into the main RetDec repository).
